---
 - name: create group
   group:
      name: superusers
      state: present
 - name: add user2
   user:
      name: user2
      append: yes
      group: sudo
      groups: superusers
      state: present
      createhome: yes
      shell: /bin/bash
 - name: set up authorized keys for the user2
   authorized_key:
     user: user2
     state: present
     key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
