---
   - name: install dns
     apt:
      update_cache: yes
      pkg:
      - dnsmasq
   - name: copy conf
     copy: src={{ dns_conf }} dest=/etc/dnsmasq.d
   - name:
     service:
      name: systemd-resolved
      state: stopped
      enabled: no
     when: ansible_distribution == "Ubuntu"
   - name: restart dns
     service:
      name: dnsmasq
      state: restarted
      enabled: yes

